.TH smbtaquery 1  "June 09, 2010" "version 0.0.1" "SYSTEM COMMANDS"
.SH SYNOPSIS
.B smbtaquery
[\-hn --host] [\-i --inet-port] [\-c --config-file] [\-q --query] [\-p --command-help] [\-d --debug-level] [\-k --key-file] 
.SH DESCRIPTION
The smbtaquery program is part of the Samba Traffic Analyzer Tools, which consists of smbtaquery and smbtamonitor(1). 
.PP
The goal of smbtaquery is to query the Samba Traffic Analyzer Daemon and display the data in a human readable form.
.PP
It is work in progress.
.PP
.SH OPTIONS
.TP
\-h \--host
Specify the host where the smbta daemon is operating on.
.TP
\-i \--inet-port
Specify the port number where the smbta daemon is operating on.
.TP
\-c \--config-file
Path to the smbtaquery config file. If not used, we assume it is $home/.smbtatools/query.config
.TP
\-q \--query
The query smbtaquery should execute. It has to be terminated with a semicolon.
.TP
\-k \--key-file
Specify the key file for smbtad
.TP
\-p \--command-help 
Display a short help text which commands are available.
.TP
\-v \--verbose
Be verbose and print all steps to the screen.
.SH EXAMPLES
.TP
smbtaquery -i 3491 -h test.yourdomain.com -q 'share /pool, total rw;'


