#define _XOPEN_SOURCE
#define _SVID_SOURCE || _BSD_SOURCE || _XOPEN_SOURCE >= 500
#define _GNU_SOURCE
#define __EXTENSIONS__
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/un.h>
#include <signal.h>
#include <getopt.h>
#include <syslog.h>
#include <sys/select.h>
#include <dlfcn.h>
#include <talloc.h>
#include <signal.h>
#include <pthread.h>
#include <curses.h>
#include "../../../iniparser3.0b/src/iniparser.h"
#include "../../../include/common.h"
#include "../../../include/version.h"
#include "monitor-fn-enum.h"
#include "configuration.h"
#include "monitor-list.h"
#include "backlog.h"
#include "network.h"
#include "visual.h"
